[[projects]]
name = "Aurora"
path = "/home/emul/Documents/Code/aurora"

[[projects]]
name = "Moments"
path = "/home/emul/Documents/Code/moments-website"

[[projects]]
name = "Ai Assistant"
path = "/home/emul/Documents/Code/Ai assistant"

[[projects]]
name = "Portfolio"
path = "/home/emul/Documents/Code/portfolio"

[[projects]]
name = "Vesrelle"
path = "/home/emul/Documents/Code/Vesrelle"
